/* tslint:disable */
/*
 * this code generated by swagger-codegen
 */
import axios from "axios";
import * as qs from "qs";
import { assign, isEmpty } from "lodash";

export const getDomain = (parameters) => {
  return parameters.$domain ? parameters.$domain : "/";
};
export const getConfig = (parameters) => {
  return parameters.$config ? parameters.$config : {};
};

export const request = (
  method,
  url,
  queryParameters,
  jsonBody,
  form,
  config
) => {
  method = method.toLowerCase();
  let keys = Object.keys(queryParameters);
  let queryUrl = url;
  if (keys.length > 0) {
    queryUrl = url + "?" + qs.stringify(queryParameters);
  }

  const headers: any = {};
  if (method != "GET") {
    headers["content-type"] = "application/x-www-form-urlencoded";
  }

  const defaultConfig = {
    method: method,
    responseType: "json",
    withCredentials: false,
    headers,
  };

  let mergedConfig;
  if (isEmpty(jsonBody) && isEmpty(form)) {
    mergedConfig = assign(defaultConfig, config);
  } else if (!isEmpty(jsonBody)) {
    /* For raw POST, PUT */
    mergedConfig = assign(
      {
        data: jsonBody,
      },
      defaultConfig,
      config
    );
  } else {
    /* For form field POST, PUT */
    mergedConfig = assign(
      {
        data: qs.stringify(form),
      },
      defaultConfig,
      config
    );
  }
  return axios(queryUrl, mergedConfig);
};

function mergeQueryParams(parameters, queryParameters) {
  if (parameters.$queryParameters) {
    Object.keys(parameters.$queryParameters).forEach(function (parameterName) {
      let parameter = parameters.$queryParameters[parameterName];
      queryParameters[parameterName] = parameter;
    });
  }
  return queryParameters;
}

export const getUserMe = function (parameters = {}) {
  let path = "/auth/me";
  let queryParameters = {};
  let jsonBody = {};
  let form = {};

  queryParameters = mergeQueryParams(parameters, queryParameters);
  return request(
    "GET",
    getDomain(parameters) + path,
    queryParameters,
    jsonBody,
    form,
    getConfig(parameters)
  );
};
